import type { Metadata } from "next";
import { ReactQueryProvider, StyledComponentsProvider } from "@/provider";
import { GlobalStyle } from "@/styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <StyledComponentsProvider>
            <GlobalStyle />
            {children}
          </StyledComponentsProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
