import type { Metadata } from "next";
import { ReactQueryProvider, StyledComponentsProvider } from "@/provider";
import Header from "@/components/@common/Header/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />

        <ReactQueryProvider>
          <StyledComponentsProvider>{children}</StyledComponentsProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
